### ISSUE TITLE
Error at Increased concurrency

### ISSUE THREAD

**Issue by pratik-n** [jhonnymertz/java-wkhtmltopdf-wrapper#10]
Testing the code at high concurrency level (>27) gives the following error in rendering pdf from html, 
Kindly do suggest for the same.
`
ERROR [2016-05-27 19:34:40,438] [dw-591 - GET /pdfrendrer?template=handlebar] [  ] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 602402206e64b42b
! java.lang.RuntimeException: Process (xvfb-run --auto-servernum --server-num=1 /usr/bin/wkhtmltopdf - -) exited with status code 1:
! 
! at br.eti.mertz.wkhtmltopdf.wrapper.Pdf.getPDF(Pdf.java:92)
! at br.eti.mertz.wkhtmltopdf.wrapper.Pdf.saveAs(Pdf.java:55)
! at dropwizard.RenderEngine.genHPdf(RenderEngine.java:103)
! at dropwizard.resources.HelloWorldResource.sayHello(HelloWorldResource.java:37)
! at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:497)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
! at org.eclipse.jetty.server.Server.handle(Server.java:499)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
! at java.lang.Thread.run(Thread.java:745)
`

**Comment by jhonnymertz** [comment]
Thanks for reporting.

The stack trace does not say too much, so I'm gonna try to reproduce the concurrency level and see what happens.

**Comment by pratik-n** [comment]
I guess at higher concurrency, there is a high cpu usage due to creation of multiple processes . Is there a way we reuse a process instead of creating, multiple wkhtmltopdf processes

**Comment by jhonnymertz** [comment]
Hi Pratik,

I was running some tests at higher concurrency level and got some errors, as you mentioned. 

It seems to be related to the external process's standard output/error streams. However, I did not figure out what could it be. I'm going to investigate deeper.

I do not know if is it possible to reuse a process instead of creating, but we can try it.
