### ISSUE TITLE
Html and Pdf tmp-Files are not getting deleted

### ISSUE THREAD

**Issue by fkajzer** [jhonnymertz/java-wkhtmltopdf-wrapper#18]
Hi,
i recently am using your wkhtmltopdf-wrapper for creating pdf files.
So far everything is fine, but since im creating a lot of files, my VM gets crowded by all the tmp.html and output.pdf files. I would like to delete those files after sending them. What do you think is the best way of dealing with this?
Thanks a lot.

**Comment by jhonnymertz** [comment]
Those html temporary files created by the wrapper during the generation should be removed by the library after the pdf creation. Despite they are created in the temp directory, as you mentioned, it can become a problem. I'll do it.

However, I think that the deletion of the generated pdf files and html sources as pages should be done by the application which is calling the library. We can make it easier by letting `saveAs` method return `File` or create a new method that returns it, so the generated pdf can be easily removed.
