### ISSUE TITLE
wkhtmltopdf --footer-* and --header-* parameters do not work

### ISSUE THREAD

**Issue by pauldub** [jhonnymertz/java-wkhtmltopdf-wrapper#2]
The wkhtmltopdf paramteres related to header and footer content do not work when there are space characters in the string, for example:

```java
pdf.addParam(new Param("--footer-center", "foo bar"));
```
Will cause an error because the "foo bar" portion of the parameter is not properly escaped and wkhtmltopdf will read it as page source urls. Trying to wrap the parameter value with `\"` or `'` was also unsuccesful.

The root cause of this is the way that `command` is built as a single string rather than an array of `String` for `Runtime#exec()`. I have forked the repository in order to apply this small patch, which you can see here: https://github.com/pauldub/java-wkhtmltopdf-wrapper/commit/03936f2e7c15fca2439ed250d18206bc2e5d0eb4 (ignore the logger which I used to debug some issues).

Would you like a PR for this?

**Comment by madmuffin1** [comment]
Hi, yes sure, please open a pull request. Jhonny or I will have a look at it and merge if it looks fine.
I would also love to have some more logging, but would prefer to have that in a separate commit/PR.

**Comment by madmuffin1** [comment]
Oh and I just had a look at your branch, I think we can safely open a PR of your whole branch. I like the adaptions you made, also the usage of process builder makes perfect sense to me - I haven't tested them in real life but code looks nice and clean.

**Comment by jhonnymertz** [comment]
Thank you for reporting it and giving a solution. It was implemented in #3.

**Comment by pauldub** [comment]
Sorry for not following up on this, but #3 looks pretty good to me, thanks!
