### ISSUE TITLE
Could you please Log4j Support or add a methode that return the error stream

### ISSUE THREAD

**Issue by Claymore1337** [jhonnymertz/java-wkhtmltopdf-wrapper#29]
Hi my main problem is that I need to Log the messages from wkhtmltopdf to trace bugs and other things in production environment.

**Comment by jhonnymertz** [comment]
It was implemented logging of library operations through logging facade slf4j. Slf4j is a simple facade or abstraction for various logging frameworks, e.g. java.util.logging, log4j and logback, so you can now plug in the desired logging framework at deployment time and catch wkhtmltopdf-wrapper logs.

Hope it works for your case.
