### ISSUE TITLE
429 too many requests error?

### ISSUE THREAD

**Issue by wuboy** [jhonnymertz/java-wkhtmltopdf-wrapper#32]
Hi - I'm currently getting this error when transferring a .jar file to our servers:

> [ERROR] Could not transfer artifact com.github.jhonnymertz:java-wkhtmltopdf-wrapper:jar:1.0.2-RELEASE from/to jitpack.io (https://jitpack.io): Failed to transfer file: https://jitpack.io/com/github/jhonnymertz/java-wkhtmltopdf-wrapper/1.0.2-RELEASE/java-wkhtmltopdf-wrapper-1.0.2-RELEASE.jar. Return code is: 429 , ReasonPhrase:Too Many Requests. -> [Help 1]

Are there many requests going on at the moment? I haven't encountered this error before when deploying our instance. 

Thanks for your help.

**Comment by jhonnymertz** [comment]
The file looks accessible and downloadable now. Probably this was a temporary problem with jitpack.
