### ISSUE TITLE
Problems with Params

### ISSUE THREAD

**Issue by alessandrots** [jhonnymertz/java-wkhtmltopdf-wrapper#34]
Hi,

I'm having trouble making the margin-top work, I tried doing the following:
// pdf.addParam (new Param ("- enable-javascript"));
// pdf.addParam (new Param ("-page-size", "A4"));
// pdf.addParam (new Param ("- margin-top", "53mm"));

or
pdf.addParam(new Param("--enable-javascript"), new Param("--page-size", "A4"), new Param("--margin-top", "53mm")););

And the text does not generate a margin at the top. 

Then what I found strange is that I commented on these parameters above and gave the same result in the pdf generation. 

But I tested at command-line and works fine.

Any idea? ou update I have todo?

**Comment by jhonnymertz** [comment]
I've tested here, and it works for me.

By using:
`pdf.addParam(new Param("--enable-javascript"), new Param("--page-size", "A4"), new Param("--margin-top", "53mm"));`
The generated command was:
`/usr/bin/wkhtmltopdf --enable-javascript --page-size A4 --margin-top 53mm http://www.google.com -`

The command generated by the wrapper seems ok. Wkhtmltopdf also works properly.

It is probably a problem in your business logic. So, check right before you generate the pdf, if the command generated by the wrapper contains all the parameters passed. You can use the method `getCommand()` on the class `Pdf` or by enabling debug-level logs for package `com.github.jhonnymertz.wkhtmltopdf.wrapper`.

If everything is ok with the generated command, try it on the command line to check whether it is a wkhtmltopdf problem.
