### ISSUE TITLE
Cleanup Tempfiles does not work from PageType.htmlAsString

### ISSUE THREAD

**Issue by kdenzel** [jhonnymertz/java-wkhtmltopdf-wrapper#35]
Jup that's it.

**Comment by kdenzel** [comment]
In 'getPdf()' you do

File temp = File.createTempFile("java-wkhtmltopdf-wrapper" + UUID.randomUUID().toString(), ".html");
FileUtils.writeStringToFile(temp, page.getSource(), "UTF-8");

in 'cleanTempFiles()' you do

if (page.getType().equals(PageType.htmlAsString)) {
    new File(page.getSource()).delete();
}

page.getSource() is not the filepath, you should set the filepath in 'getPdf' after FileUtils.writeStringToFile

**Comment by jhonnymertz** [comment]
Thanks for reporting the bug and possible solution!
I would encourage you to submit a pull request addressing it.

**Comment by kdenzel** [comment]
Ok i will do so.

**Comment by jhonnymertz** [comment]
Solved
