### ISSUE TITLE
Problems with header and footers options if the parameters consist of spaces

### ISSUE THREAD

**Issue by chingyk** [jhonnymertz/java-wkhtmltopdf-wrapper#38]
When im trying to set the params as below
`new Param("--replace", "headerTitle", "testing spaces parameters");`

where i have a header.html setup
`<span class="headerTitle"></span>`

These errors shows up
Error: Failed to load http://parameters/, with network status code 3 and http status code 0 - Host parameters not found
Error: Failed loading page http://parameters (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed to load http://spaces/, with network status code 3 and http status code 0 - Host spaces not found
Error: Failed loading page http://spaces (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError

it seems like the strings after the 1st word is recognised as http value.
and so i tried a standard param like 
`new Param("--footer-right", "Page [page] of [toPage]");`
the same error occurs. 
Can i get any help on this? ty.

Edited: Im running this on macOS High SIerra

**Comment by OhadR** [comment]
the --replace command works? if you write something like
`new Param("--replace", "headerTitle", "testing spaces parameters");`

i do not see that the URL contains "headerTitle" key... only : 

['page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages']

**Comment by jhonnymertz** [comment]
@OhadR the best way to check whether it is supported or not is to check the generated command.

The wrapper essentially creates a wkhtmltopdf command based on the params, and then executes this command as a system command. You can use the method getCommand() on the class Pdf to verify the command string generated before generating the PDF. Then, you can execute the command manually into a command terminal on your machine and compare the results.

So please, provide the command which is being generated and the results you obtained when executing the command into your machine. This will guide the bug investigation. Thanks!

**Comment by OhadR** [comment]
Thanks a ton, @jhonnymertz !

In the past couple of days this is exactly what I have done. I found that the 'replace' command is working, and that your java-wrapper is awesome!

thanks again.
