### ISSUE TITLE
wkhtmltopdf command was not found in your classpath

### ISSUE THREAD

**Issue by bibichuan** [jhonnymertz/java-wkhtmltopdf-wrapper#41]
win10系统中已经将wkhtmltopdf路径加入到path中了，可以在cmd中使用wkhtmltopdf，但是还是提示wkhtmltopdf command was not found in your classpath. Verify its installation or initialize wrapper configurations with correct path/to/wkhtmltopdf

**Comment by bibichuan** [comment]
这是个bug,在win10中的powershell中，应该用where.exe代替where

**Comment by bibichuan** [comment]
where wkhtmltopdf,得到的错误信息是： 用提供的模式无法找到文件。

**Comment by ktth159** [comment]
착짱죽짱

**Comment by arozak25** [comment]
how you solve this? @bibichuan

**Comment by jhonnymertz** [comment]
possibly fixed on #50
