### ISSUE TITLE
unable to generate pdf in case of unknown content error

### ISSUE THREAD

**Issue by atif92** [jhonnymertz/java-wkhtmltopdf-wrapper#42]
when I use wkhtml outside java it created the pdf despite of the unknown content error but now when i came to know of this API, i implemented it in my project but in case of unknown content error it is not even generating the pdf file.

**Comment by jhonnymertz** [comment]
Sorry for the late reply, but were you able to solve the problem? If not, can you give more information on how to reproduce it to investigate?
Thanks!
