### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by rafaeldiassoares** [jhonnymertz/java-wkhtmltopdf-wrapper#5]
how to return it for javascript to print the pdf? thanks!

https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/blob/master/src/tests/java/br/eti/mertz/wkhtmltopdf/wrapper/PdfTest.java

**Comment by jhonnymertz** [comment]
I don't know which type of web stack you are using, but the file can be written on the backend disk, so you can read and return it as a byte array or a file. 

If you are using Spring, something like that should work:

```java
@ResponseBody
    @RequestMapping(value = "/pdf", method = RequestMethod.GET,
            produces = "application/pdf")
    public FileSystemResource getPdf(HttpServletResponse response)
            throws IOException, InterruptedException {

        response.addHeader("Content-Disposition", "attachment; filename=\"pdf.pdf\"");

        File pdfFile = new File("pdf.pdf");

        FileSystemResource fs = new FileSystemResource(pdfFile);

        return fs;
    }
```

This link can be useful aswell: http://stackoverflow.com/questions/16652760/return-generated-pdf-using-spring-mvc

**Comment by rafaeldiassoares** [comment]
Thanks for your help.
