### ISSUE TITLE
Lingering temporary html file

### ISSUE THREAD

**Issue by Vynny** [jhonnymertz/java-wkhtmltopdf-wrapper#52]
Environment
---
java version: openjdk 1.8.0_181
java-wkhtmltopdf-wrapper version: 1.1.9-RELEASE
wkhtmltopdf version: 0.12.5

Expected Behavior
---
Calling Pdf.saveAs() with html added via addPageFromString() cleans up all temporary files created to generate the pdf file.

Actual Behavior
---
Two java-wkhtmltopdf-wrapper*.html temporary files are created, but only one of them is cleaned up.

Likely Cause
---
In Pdf.getPDF() the command is logged on line 169 which requires a call to getCommand(). This calls getCommandAsArray() which creates a temporary file for every page. 

When getCommandAsArray() is called on line 170, this creates yet another temporary file. cleanTempFiles() only cleans up one of these files, which leaves a lingering temporary html file.

**Comment by jhonnymertz** [comment]
Thank you for the detailed report and investigation! Support is available on a best-effort basis and I'll try to fix it as soon as possible. Pull requests are welcomed!
