### ISSUE TITLE
Chart js  conversion not working 

### ISSUE THREAD

**Issue by dravidnsk** [jhonnymertz/java-wkhtmltopdf-wrapper#67]
Not able create chart 

public class PDFCreation1 {
    public static void main(String[] args) throws IOException, InterruptedException {
        Pdf pdf = new Pdf(new WrapperConfig("wkhtmltopdf"));
        pdf.cleanAllTempFiles();
    

        pdf.addParam(new Param("--enable-javascript"));
       // pdf.addTocParam(new Param("--xsl-style-sheet", "my_toc.xsl"));

        // pdf.addParam();
        pdf.addPageFromFile("file:///C:/Users/sathishkumar_n/Desktop/pipechart.html");
        pdf.saveAs("C:\\Nsk\\PDF\\output1.pdf");
    }

}

[pipeChart.zip](https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/files/5396394/pipeChart.zip)
[output1.pdf](https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/files/5396396/output1.pdf)

**Environment (please complete the following information):**
 - java-wkhtmltopdf-wrapper version:1.1.12
 - wkhtmltopdf version: 0.12.6

**Comment by jhonnymertz** [comment]
Hey @dravidnsk, thanks for raising the issue and providing details to reproduce. Actually, it seems something with `wkhtmltopdf`, I was able to reproduce it with the command:

`wkhtmltopdf.exe --enable-javascript pipeChart.html output.pdf` - this is actually the command generated by the library.

The chart does not render indeed, and it seems to me something with the javascript processing. I tried another configuration such as `--javascript-delay 5000` and have no success. There are multiple reports on charts and other javascript-based elements no being rendered properly, such as https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1964.

Sorry for this, but it is not related to the wrapper. Hope you can find your answer in the wkhtmltopdf community.
