### ISSUE TITLE
Output and Error Stream data union

### ISSUE THREAD

**Issue by bioker** [jhonnymertz/java-wkhtmltopdf-wrapper#7]
Hi, thanks for the wrapper, I used it as an example for writing an easier option for my needs. I encountered an error and did not have time to understand it. And so I decided just to warn you. Let's start with the fact that the wkhtmltopdf on my server just does not start for this reason: [https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037]. The solution was to use the wkhtmltopdf with the xvfb-run. It was necessary to change your source code for future use. You can track the changes in my repository. One problem has been resolved but there was another, for still unknown reason, the output stream is combined. data that should be in the console fell in the file. To avoid this, it was decided to abandon the error stream. I could not figure out the cause of the. But I think you can just keep it in mind.

**Comment by jhonnymertz** [comment]
Thanks for sharing! I was already approached to support xvfb and your primary attempt and report will be useful.

Actually, this error is related to using wkhtmltopdf without a X server, which is required. Then, xvfb run a virtual display in memory without showing any screen output and do the job.

I'll track your changes and try to figure out what is going on with the error stream.

Thanks!

**Comment by jhonnymertz** [comment]
Based on your implementation, I've implemented support for xvfb. However, I do not have the problem that you mentioned in error stream, that file and error were being mixed.

**Comment by bioker** [comment]
So, I think it means the problem is located beyond this code. But the enhancement I think be helpful. Thank you for your prompt response. I will try resolve my problem  because it's appears again. Even without using the errorStream of process
