### ISSUE TITLE
Ability to accept custom wkhtmltopdf command

### ISSUE THREAD

**Issue by evaldasu** [jhonnymertz/java-wkhtmltopdf-wrapper#76]
**Is your feature request related to a problem? Please describe.**
When we're running our application code locally and in remote servers we do not use locally installed `wkhtmltopdf` command line tool, but instead use docker image that has that tool.
The command we pass to the `WrapperConfig` looks like this `docker container exec wam_wkhtmltopdf wkhtmltopdf`, where `wam_wkhtmltopdf` refers to the container of docker image [cs2ag/docker-wkhtmltopdf](https://hub.docker.com/r/cs2ag/docker-wkhtmltopdf).

After [this change](https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/commit/05babff0d13c8393844bfd864788d50ff0c10f96) it seems to be no longer working, since we're getting `java.io.IOException: Cannot run program "docker container exec wam_wkhtmltopdf wkhtmltopdf": error=2, No such file or directory`.

Here's the debugger comparison of `Runtime.getRuntime().exec()` call, comparing 1.1.4 (working) and 1.1.14 (not working):
![image](https://user-images.githubusercontent.com/107461273/209660956-19129d57-0540-4621-bda6-1b3414c6ee2a.png)

**Describe the solution you'd like**
We would like to use this wrapper not only with locally installed `wkhtmltopdf` command line tool, but also with docker containers.

I was thinking about changes in `WrapperConfig` to maybe parse the `wkhtmltopdfCommand` and return array of strings instead of string. Then do `commandLine.addAll(wrapperConfig.getWkhtmltopdfCommandAsArray());`

**Describe alternatives you've considered**
* We considered installing `wkhtmltopdf` locally for each developer, as well as in remote servers where our app is running, but this seems to defeat the purpose of why we're using docker.
* ~~The only real alternative we see right now is to use [Mulesoft repository](https://mvnrepository.com/artifact/com.github.jhonnymertz/java-wkhtmltopdf-wrapper?repo=mulesoft-public) and pull 1.1.4 from there.~~
* Use obsolete and often unstable nexus.pentaho repositories, which we've used before. There's a 1.1.4 version in there.
* Open a PR to this repository with a suggested fix

**Additional context**
As of now our team was using a  1.1.4 version which was fetched from some obscure and unstable repository. We recently changed that and decided to use maven central repositories as much as possible. We did not find a 1.1.4 in there so we went with the latest version (1.1.14).

**Comment by evaldasu** [comment]
Mulesoft repositories doesn't seem to have 1.1.4-RELEASE version, even though it does on mvnrepository

**Comment by jhonnymertz** [comment]
> Mulesoft repositories doesn't seem to have 1.1.4-RELEASE version, even though it does on mvnrepository

Hey! Thanks for opening the issue and providing a detailed report. Regarding old versions, such as 1.1.4, this was prior to the setup of publishing the library jars via OSSRH. For these older versions, I'd suggest trying to get it via jitpack: https://jitpack.io/#jhonnymertz/java-wkhtmltopdf-wrapper/1.1.4-RELEASE.

Try it and let me know. For now, I think publishing an old version of the library into OSSRH (to be available via maven repositories) is not a good idea as this will receive a newer publish date and may confuse people trying to use it.

**Comment by evaldasu** [comment]
I've tried this approach and it does fetch the required version (1.1.4-RELEASE). While you're looking at the PR I've submitted, I'll use this solution to have a working app. Thanks!

**Comment by jhonnymertz** [comment]
@evaldasu, this should be ok in the `1.1.15-RELEASE`, which includes your fix #77.
